["1️⃣ 环境配置"]
title = "1️⃣ 环境配置"
emoji = ":simple-clion:"
info = ""
cover = ""
path = "./🍏 C&C++/1️⃣ 环境配置"

["2️⃣ 基础编程"]
title = "2️⃣ 基础编程"
emoji = ":simple-c:"
info = ""
cover = ""
path = "./🍏 C&C++/2️⃣ 基础编程"

["3️⃣ C工程API文档"]
title = "3️⃣ C工程API文档"
emoji = ":simple-doxygen:"
info = ""
cover = ""
path = "./🍏 C&C++/3️⃣ C工程API文档"

["4️⃣ 嵌入式编程"]
title = "4️⃣ 嵌入式编程"
emoji = ":simple-arduino:"
info = ""
cover = ""
path = "./🍏 C&C++/4️⃣ 嵌入式编程"
