["1️⃣ koko-learn"]
title = "1️⃣ koko-learn"
emoji = ""
info = ""
cover = ""
path = "./7MyScripts/1️⃣ koko-learn"

["2️⃣ koko-film"]
title = "2️⃣ koko-film"
emoji = ""
info = ""
cover = ""
path = "./7MyScripts/2️⃣ koko-film"

["2️⃣️ 图片压缩"]
title = "2️⃣️ 图片压缩"
emoji = ""
info = ""
cover = ""
path = "./7MyScripts/2️⃣️ 图片压缩"

["3️⃣️ 图片水印"]
title = "3️⃣️ 图片水印"
emoji = ""
info = ""
cover = ""
path = "./7MyScripts/3️⃣️ 图片水印"
