["A.md"]
title = "🎃️ 图片压缩"
emoji = ""
info = ""
cover = ""
path = "./7MyScripts/2️⃣️ 图片压缩/A.md"
comments = true

["B.md"]
title = "🎃️ 图片压缩(tinypng)"
emoji = ""
info = ""
cover = ""
path = "./7MyScripts/2️⃣️ 图片压缩/B.md"
comments = true
