["A.md"]
title = "🤷🏻 NGBoost总览"
emoji = ""
info = ""
cover = ""
path = "./👺 机器学习/8️⃣ NGBoost/A.md"
date = "2024.08.28"
comments = true

["B.ipynb"]
title = "B.ipynb"
emoji = ""
info = ""
cover = ""
path = "./👺 机器学习/8️⃣ NGBoost/B.ipynb"

["C.ipynb"]
title = "C.ipynb"
emoji = ""
info = ""
cover = ""
path = "./👺 机器学习/8️⃣ NGBoost/C.ipynb"

["D.ipynb"]
title = "D.ipynb"
emoji = ""
info = ""
cover = ""
path = "./👺 机器学习/8️⃣ NGBoost/D.ipynb"

["E.ipynb"]
title = "E.ipynb"
emoji = ""
info = ""
cover = ""
path = "./👺 机器学习/8️⃣ NGBoost/E.ipynb"
