[0ML_Noun]
title = "0ML_Noun"
emoji = ""
info = ""
cover = ""
path = "./5ML/0ML_Noun"

["0️⃣ ML相关概念"]
title = "0️⃣ ML相关概念"
emoji = ":simple-scikitlearn:"
info = "机器学习是一种通过数据训练模型，使计算机能够自动改进和预测的技术，广泛应用于图像识别、自然语言处理等领域。"
cover = ""
path = "./👺 机器学习/0️⃣ ML相关概念"

[10sklearn]
title = "10sklearn"
emoji = ""
info = ""
cover = ""
path = "./5ML/10sklearn"

[11MLOps]
title = "11MLOps"
emoji = ""
info = ""
cover = ""
path = "./5ML/11MLOps"

[12pytorch]
title = "12pytorch"
emoji = ""
info = ""
cover = ""
path = "./5ML/12pytorch"

[1DataSets]
title = "1DataSets"
emoji = ""
info = ""
cover = ""
path = "./5ML/1DataSets"

["1️⃣ 开源数据集"]
title = "1️⃣ 开源数据集"
info = "开源数据集是指其许可证允许任何人免费使用、分发和修改的数据集。它们对于机器学习、数据分析和其他研究领域至关重要。"
emoji = ":simple-kaggle:"
cover = ""
path = "./👺 机器学习/1️⃣ 开源数据集"

[2FeaSelect]
title = "2FeaSelect"
emoji = ""
info = ""
cover = ""
path = "./5ML/2FeaSelect"

["2️⃣ 特征选择"]
title = "2️⃣ 特征选择"
emoji = ":simple-futurelearn:"
info = ""
cover = ""
path = "./👺 机器学习/2️⃣ 特征选择"

[3semi_learn]
title = "3semi_learn"
emoji = ""
info = ""
cover = ""
path = "./5ML/3semi_learn"

["3️⃣ 半监督学习"]
title = "3️⃣ 半监督学习"
emoji = ":simple-namecheap:"
info = ""
cover = ""
path = "./👺 机器学习/3️⃣ 半监督学习"

[4ensemble]
title = "4ensemble"
emoji = ""
info = ""
cover = ""
path = "./5ML/4ensemble"

["4️⃣ 集成学习"]
title = "4️⃣ 集成学习"
info = "集成学习通过组合多个模型（如决策树、神经网络）来提高预测性能和稳定性，常见方法包括Bagging、Boosting和Stacking。"
emoji = ":simple-scikitlearn:"
cover = ""
path = "./👺 机器学习/4️⃣ 集成学习"

[5param_opti]
title = "5param_opti"
emoji = ""
info = ""
cover = ""
path = "./5ML/5param_opti"

["5️⃣ 超参数优化"]
title = "5️⃣ 超参数优化"
info = "超参数优化是指在ML中，通过调整模型的超参数来提升模型性能的过程，常用方法有网格搜索、随机搜索和贝叶斯优化等。"
emoji = ":simple-scikitlearn:"
cover = ""
path = "./👺 机器学习/5️⃣ 超参数优化"

[6explainable_ml]
title = "6explainable_ml"
emoji = ""
info = ""
cover = ""
path = "./5ML/6explainable_ml"

["6️⃣ 模型可解释性"]
title = "6️⃣ 模型可解释性"
info = "模型可解释性是指解释机器学习模型决策过程的能力，帮助识别模型的决策依据，常用方法包括LIME、SHAP和特征重要性分析。"
emoji = ":simple-scikitlearn:"
cover = ""
path = "./👺 机器学习/6️⃣ 模型可解释性"

[7confidence_learning]
title = "7confidence_learning"
emoji = ""
info = ""
cover = ""
path = "./5ML/7confidence_learning"

["7️⃣ 置信学习"]
title = "7️⃣ 置信学习"
info = "置信学习是一种机器学习方法，通过估计模型预测的置信度来提高决策的可靠性，常用于处理不确定性和提高模型的鲁棒性。"
emoji = ":simple-scikitlearn:"
cover = ""
path = "./👺 机器学习/7️⃣ 置信学习"

[8NGBoost]
title = "8NGBoost"
emoji = ""
info = ""
cover = ""
path = "./5ML/8NGBoost"

["8️⃣ NGBoost"]
title = "8️⃣ NGBoost"
info = "NGBoost（Natural Gradient Boosting）是一种基于自然梯度的提升方法，直接预测概率分布，提高模型预测不确定性估计能力。"
emoji = ":simple-scikitlearn:"
cover = ""
path = "./👺 机器学习/8️⃣ NGBoost"

[9CatBoost]
title = "9CatBoost"
emoji = ""
info = ""
cover = ""
path = "./5ML/9CatBoost"

["9️⃣ CatBoost"]
title = "9️⃣ CatBoost"
info = "CatBoost是一种高效的梯度提升决策树算法，特别擅长处理分类特征，具有高精度和快速训练的优点，广泛应用于各种机器学习任务。"
emoji = ":simple-scikitlearn:"
cover = ""
path = "./👺 机器学习/9️⃣ CatBoost"

[MLOps]
title = "MLOps"
emoji = ""
info = ""
cover = ""
path = "./👺 机器学习/MLOps"

[pytorch]
title = "pytorch"
emoji = ""
info = ""
cover = ""
path = "./👺 机器学习/pytorch"

["🔟 scikit-learn"]
title = "🔟 scikit-learn"
emoji = ":simple-scikitlearn:"
info = ""
cover = ""
path = "./👺 机器学习/🔟 scikit-learn"
