["1️⃣ 开源数据集"]
info = "一些常见数据集的简单使用"

["3️⃣ ML相关概念"]
info = "一些机器学习相关概念、理解"

["4️⃣ 集成学习"]
info = ""

["5️⃣ 超参数优化"]
info = ""

["6️⃣ 模型可解释性"]
info = ""

["7️⃣ 置信学习"]
info = ""

["8️⃣ NGBoost"]
info = ""

["9️⃣ CatBoost"]
info = ""

["index.md"]
info = ""
