[".ipynb_checkpoints"]
info = ""

["0️⃣ PyCharm配置"]
info = ""

["0️⃣ 基础编程"]
info = ""

["0️⃣ 扩展库"]
info = ""

["1️⃣  Rye相关"]
info = ""

["2️⃣ Conda相关"]
info = ""

["3️⃣ pip相关"]
info = ""

["5️⃣ Python可视化"]
info = ""

["6️⃣ Python科学计算"]
info = ""

["7️⃣ Python网络编程"]
info = ""

["8️⃣ Python GUI编程"]
info = ""

["9️⃣ Python硬件编程"]
info = ""

["🔟 其他"]
info = ""
