["0️⃣ 开源软件"]
info = "开源软件是指源代码可以被公众查看、修改和增强的软件，它鼓励社区合作和创新。这类软件通常遵循特定的开源许可证，如GNU通用公共许可证（GPL）。"
emoji = ":simple-opensourceinitiative:"

["1️⃣ Linux(Ubuntu)"]
info = "Ubuntu是一个基于Linux的开源操作系统，以其用户友好的界面和强大的社区支持而闻名。它适用于多种设备，包括桌面、服务器和云环境，提供了免费的更新和安全补丁。"
emoji = ":simple-ubuntu:"

["2️⃣ WSL"]
info = "WSL（Windows Subsystem for Linux）是微软开发的一项功能，它允许用户在Windows 10和Windows 11上原生运行Linux环境。"
emoji = ":simple-linux:"

["3️⃣ Windows 10"]
info = ""
emoji = ":fontawesome-brands-windows:"

["4️⃣ Windows11"]
info = ""
emoji = ":fontawesome-brands-windows:"

["5️⃣ Git"]
info = "Git是一个开源的分布式版本控制系统，用于有效、高速地处理从小到大的项目版本管理。它由Linus Torvalds创建，支持分支和合并操作，广泛用于软件开发中以协调代码变更和多人协作。"
emoji = ":simple-git:"

["6️⃣ macOS"]
info = ""
emoji = ":material-apple:"

["7️⃣ 英雄联盟"]
info = ""
emoji = ":simple-leagueoflegends:"
