["A.md"]
title = "😆 离群值对模型的影响"
emoji = ""
info = ""
cover = ""
path = "./5ML/0ML_Noun/A.md"
comments = true

["B.md"]
title = "😎 CatBoost参数"
emoji = ""
info = ""
cover = ""
path = "./5ML/0ML_Noun/B.md"
comments = true

["C.ipynb"]
title = "C.ipynb"
emoji = ""
info = ""
cover = ""
path = "./5ML/0ML_Noun/C.ipynb"

["D.md"]
title = "🧸 自然梯度&常规梯度"
emoji = ""
info = ""
cover = ""
path = "./5ML/0ML_Noun/D.md"
comments = true

["E.md"]
title = "😖 相关系数与决定系数"
emoji = ""
info = ""
cover = ""
path = "./5ML/0ML_Noun/E.md"
comments = true

["F.md"]
title = "广义加性模型"
emoji = ""
info = ""
cover = ""
path = "./5ML/0ML_Noun/F.md"
date = "2024.10.20"
comments = true

["G.md"]
title = "线性模型"
emoji = ""
info = ""
cover = ""
path = "./5ML/0ML_Noun/G.md"
date = "2024.10.20"
comments = true

["H.md"]
title = "信息熵：度量不确定性"
emoji = ""
info = ""
cover = ""
path = "./5ML/0ML_Noun/H.md"
date = "2024.10.20"
comments = true

["I.md"]
title = "预测概率与对数概率"
emoji = ""
info = ""
cover = ""
path = "./5ML/0ML_Noun/I.md"
date = "2024.10.20"
comments = true

["J.md"]
title = "学习率调度器"
emoji = ""
info = ""
cover = ""
path = "./5ML/0ML_Noun/J.md"
date = "2024.12.16"
comments = true

["K.md"]
title = "平均损失"
emoji = ""
info = ""
cover = ""
path = "./5ML/0ML_Noun/K.md"
date = "2024.12.16"
comments = true

["L.md"]
title = "随机最大池化"
emoji = ""
info = ""
cover = ""
path = "./5ML/0ML_Noun/L.md"
date = "2024.12.16"
comments = true

["M.md"]
title = "pytorch推理模式"
emoji = ""
info = ""
cover = ""
path = "./5ML/0ML_Noun/M.md"
date = "2024.12.16"
comments = true
