[1sp]
title = "1sp"
emoji = ""
info = ""
cover = ""
path = "./6SignalP/1sp"

["1️⃣ 生物医学信号处理"]
title = "1️⃣ 生物医学信号处理"
emoji = ":simple-scipy:"
info = ""
cover = ""
path = "./🍒 信号处理/1️⃣ 生物医学信号处理"

[2base]
title = "2base"
emoji = ""
info = ""
cover = ""
path = "./6SignalP/2base"

["2️⃣ 基础知识"]
title = "2️⃣ 基础知识"
emoji = ":simple-scipy:"
info = ""
cover = ""
path = "./🍒 信号处理/2️⃣ 基础知识"

[3filter]
title = "3filter"
emoji = ""
info = ""
cover = ""
path = "./6SignalP/3filter"

["3️⃣ 滤波器设计"]
title = "3️⃣ 滤波器设计"
emoji = ":simple-scipy:"
info = ""
cover = ""
path = "./🍒 信号处理/3️⃣ 滤波器设计"

[4experience]
title = "4experience"
emoji = ""
info = ""
cover = ""
path = "./6SignalP/4experience"

["4️⃣ 常用技巧"]
title = "4️⃣ 常用技巧"
emoji = ":simple-scipy:"
info = ""
cover = ""
path = "./🍒 信号处理/4️⃣ 常用技巧"
