["A.md"]
title = "📪 Win10常见报错及修复"
emoji = ""
info = ""
cover = ""
path = "../docs/🎀 软件及配置/3️⃣ Windows 10/A.md"
comments = true

["B.md"]
title = "⛈️ WindowsTerminal美化"
emoji = ""
info = ""
cover = ""
path = "../docs/🎀 软件及配置/3️⃣ Windows 10/B.md"
comments = true

["BB.md"]
title = "🖊️ SSH配置"
emoji = ""
info = ""
cover = ""
path = "../docs/🎀 软件及配置/3️⃣ Windows 10/BB.md"
comments = true

["C.md"]
title = "⌚ Windows美化"
emoji = ""
info = ""
cover = ""
path = "../docs/🎀 软件及配置/3️⃣ Windows 10/C.md"
comments = true

["D.md"]
title = "☔ 修改PPT图片导出分辨率"
emoji = ""
info = ""
cover = ""
path = "../docs/🎀 软件及配置/3️⃣ Windows 10/D.md"
comments = true

["E.md"]
title = "☔ 国家标准参考文献格式"
emoji = ""
info = ""
cover = ""
path = "../docs/🎀 软件及配置/3️⃣ Windows 10/E.md"
date = 2022-10-04
comments = true
