["1️⃣ 环境配置"]
info = ""
emoji = ":frog:"

["2️⃣ MkDocs"]
info = ""
emoji = ":simple-materialformkdocs:"

["3️⃣ MinIO"]
info = ""
emoji = ":simple-minio:"

["4️⃣ Markdown"]
info = ""
emoji = ":simple-markdown:"

["5️⃣ Apache"]
info = ""
emoji = ":simple-apache:"

["6️⃣ Hexo"]
info = ""
emoji = ":simple-hexo:"

["7️⃣ 字体"]
info = ""
emoji = ":fontawesome-solid-font:"

["8️⃣ Notion"]
info = ""
emoji = ":simple-notion:"
