[1env]
title = "1env"
emoji = ""
info = ""
cover = ""
path = "./4HTML/1env"

["1️⃣ 环境配置"]
title = "1️⃣ 环境配置"
info = ""
emoji = ":simple-javascript:"
cover = ""
path = "./🎈 前端/1️⃣ 环境配置"

[2MkDocs]
title = "2MkDocs"
emoji = ""
info = ""
cover = ""
path = "./4HTML/2MkDocs"

["2️⃣ MkDocs"]
title = "2️⃣ MkDocs"
info = ""
emoji = ":simple-materialformkdocs:"
cover = ""
path = "./🎈 前端/2️⃣ MkDocs"

[3MinIO]
title = "3MinIO"
emoji = ""
info = ""
cover = ""
path = "./4HTML/3MinIO"

["3️⃣ MinIO"]
title = "3️⃣ MinIO"
info = ""
emoji = ":simple-minio:"
cover = ""
path = "./🎈 前端/3️⃣ MinIO"

[4Markdown]
title = "4Markdown"
emoji = ""
info = ""
cover = ""
path = "./4HTML/4Markdown"

["4️⃣ Markdown"]
title = "4️⃣ Markdown"
info = ""
emoji = ":simple-markdown:"
cover = ""
path = "./🎈 前端/4️⃣ Markdown"

[5Apache]
title = "5Apache"
emoji = ""
info = ""
cover = ""
path = "./4HTML/5Apache"

["5️⃣ Apache"]
title = "5️⃣ Apache"
info = ""
emoji = ":simple-apache:"
cover = ""
path = "./🎈 前端/5️⃣ Apache"

[6Hexo]
title = "6Hexo"
emoji = ""
info = ""
cover = ""
path = "./4HTML/6Hexo"

["6️⃣ Hexo"]
title = "6️⃣ Hexo"
info = ""
emoji = ":simple-hexo:"
cover = ""
path = "./🎈 前端/6️⃣ Hexo"

[7Fonts]
title = "7Fonts"
emoji = ""
info = ""
cover = ""
path = "./4HTML/7Fonts"

["7️⃣ 字体"]
title = "7️⃣ 字体"
info = ""
emoji = ":fontawesome-solid-font:"
cover = ""
path = "./🎈 前端/7️⃣ 字体"

[8Notion]
title = "8Notion"
emoji = ""
info = ""
cover = ""
path = "./4HTML/8Notion"

["8️⃣ Notion"]
title = "8️⃣ Notion"
info = ""
emoji = ":simple-notion:"
cover = ""
path = "./🎈 前端/8️⃣ Notion"
