["1️⃣ Linux"]
info = ""

["2️⃣ WSL"]
info = ""

["3️⃣ Windows 10"]
info = ""

["4️⃣ Windows11"]
info = ""

["5️⃣ Git"]
info = ""

["info.toml"]
info = ""

["🆒 开源软件"]
info = ""

["index.md"]
info = ""
